name: Deploy Theme to Staging

on:
  pull_request:
    branches:
      - staging
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.LIGHTSAIL_HOST}}
          username: ${{secrets.LIGHTSAIL_USER}}
          key: ${{secrets.LIGHTSAIL_SSH_KEY}}
          script: |
            cd /var/www/html/wp-content/themes/kctennisblastteam6
            git pull origin staging


